version: "3.9"

services:
  # -------------------------
  # Database (Postgres)
  # -------------------------
  db:
    image: postgres:15
    container_name: my_postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  # -------------------------
  # Backend (Node + Express + OCR client)
  # -------------------------
  backend:
    build: ./backend
    container_name: my_backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "start"]

  # -------------------------

  # -------------------------
  # Frontend (React)
  # -------------------------
  frontend:
    build: ./frontend
    container_name: my_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

# -------------------------
# Volumes (persist Postgres data)
# -------------------------
volumes:
  postgres_data:
